server:
  port: 8080
  servlet:
    context-path: /redisLearn
spring:
  application:
    name: redisLearn

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/et?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456

  redis:
    database: 0               #Redis 索引（0~15，默认为0）
    password: 123456
    timeout: 5000
    cluster:
      nodes:
        - 192.168.43.172:6380
        - 192.168.43.172:6381
        - 192.168.43.172:6382
        - 192.168.43.172:6383
        - 192.168.43.172:6384
        - 192.168.43.172:6385
    lettuce:                  #使用 lettuce 连接池
      pool:
        max-active: 20        #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1          #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0           #连接池中的最大空闲连接
        max-idle: 10          #连接池中的最小空闲连接
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

